{{- if semverCompare ">=1.21.0" ( trimPrefix "v" .Capabilities.KubeVersion.Version ) }}
apiVersion: batch/v1
{{- else -}}
apiVersion: batch/v1
{{- end }}
kind: CronJob
metadata:
  name: {{ include "common.fullname" ( dict "root" $ "service" .Values ) }}
  {{- include "common.metadata" ( dict "root" $ "service" .Values ) | nindent 2 }}
spec:
  schedule: {{ .Values.schedule | quote }}
  successfulJobsHistoryLimit: {{ .Values.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.failedJobsHistoryLimit }}
  concurrencyPolicy: {{ .Values.concurrencyPolicy }}
  jobTemplate:
    spec:
      backoffLimit: {{ .Values.backoffLimit }}
      template:
        metadata: {{- include "common.podMetadata" ( dict "root" $ "service" .Values ) | nindent 10 }}
        spec:
          {{- include "common.podConfig" ( dict "root" $ "service" .Values ) | nindent 10 }}
          restartPolicy: {{ .Values.restartPolicy }}
          {{- if .Values.initContainers }}
          initContainers:
          {{- range $name, $config := .Values.initContainers }}
            - name: {{ $name }}
              {{- include "common.containerConfig" ( dict "root" $ "container" $config ) | nindent 14 }}
              {{- with $config.command }}
              command: {{ . | toYaml | nindent 16 }}
              {{- end }}
              {{- with $config.args }}
              args: {{ . | toYaml | nindent 16 }}
              {{- end }}
              {{- with $config.volumeMounts }}
              volumeMounts:
              {{- include "common.dictToList" ( dict "keyName" "mountPath" "contents" . ) | nindent 16 -}}
              {{- end -}}
              {{- with $config.volumeDevices -}}
              volumeDevices:
              {{- include "common.dictToList" ( dict "keyName" "devicePath" "contents" . ) | nindent 16 }}
              {{- end }}
          {{- end }}
          {{- end }}
          containers:
          {{- range $name, $config := .Values.containers }}
            - name: {{ $name }}
              {{- include "common.containerConfig" ( dict "root" $ "container" $config ) | nindent 14 }}
              {{- with $config.command }}
              command:
                {{- . | toYaml | nindent 16 }}
              {{- end }}
              {{- with $config.args }}
              args:
                {{- . | toYaml | nindent 16 }}
              {{- end }}
              {{- with $config.volumeMounts }}
              volumeMounts:
              {{- include "common.dictToList" ( dict "keyName" "mountPath" "contents" . ) | nindent 16 }}
              {{- end }}
              {{- with $config.volumeDevices }}
              volumeDevices:
              {{- include "common.dictToList" ( dict "keyName" "devicePath" "contents" . ) | nindent 16 }}
              {{- end }}
              {{- with $config.ports }}
              ports:
              {{- include "common.dictToList" ( dict "contents" . ) | nindent 16 }}
              {{- end }}
              {{- with $config.workingDir }}
              workingDir: {{ . }}
              {{- end }}
          {{- end }}
          {{- with .Values.volumes }}
          volumes:
          {{- include "common.dictToList" ( dict "contents" . ) | nindent 12 }}
          {{- end }}
